CC.UI.Webhost/Models/Announcement.cs
namespace CC.UI.Webhost.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

    public class Announcement
    {
        public int ID { get; set; }

        public int EventID { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "title")]
        public string Title { get; set; }

        [Required]
        [StringLength(2000)]
        [DataType(DataType.MultilineText)]
        [Display(Name = "content")]
        [AllowHtml]
        public string Content { get; set; }

        [Required]
        [Display(Name = "publish date")]
        public DateTime PublishDate { get; set; }
    }
}

CC.UI.Webhost/Controllers/AnnouncementController.cs
using CC.Service.Webhost.CodeCampSvc;

namespace CC.UI.Webhost.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    using CC.UI.Webhost.Models;

    public class AnnouncementController : BaseController
    {
        public AnnouncementController(ICodeCampService service, ICodeCampServiceRepository repo) : base(service, repo) { }


        //
        // GET: /Announcement/
        public ActionResult Index(int eventid)
        {
            var announcements = service.GetAnnouncements(eventid);

            List<Announcement> model = new List<Announcement>();

            foreach (var announcement in announcements)
                model.Add(new Announcement()
                {
                    ID = announcement.ID,
                    EventID = announcement.EventID,
                    Title = announcement.Title,
                    Content = announcement.Content,
                    PublishDate = announcement.PublishDate
                });

            return View(model);
        }

        //
        // GET: /Announcement/Details/5

        public ActionResult Details(int id)
        {
            var announcement = service.GetAnnouncement(id);

            Announcement model = new Announcement()
            {
                ID = announcement.ID,
                EventID = announcement.EventID,
                Title = announcement.Title,
                Content = announcement.Content,
                PublishDate = announcement.PublishDate
            };

            return View(model);
        }

        //
        // GET: /Announcement/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create(int eventid)
        {
            Announcement model = new Announcement();

            model.EventID = eventid;
            model.PublishDate = DateTime.Today;

            return View(model);
        }

        //
        // POST: /Announcement/Create

        [HttpPost]
        public ActionResult Create(Announcement announcement)
        {
            try
            {
                service.CreateAnnouncement(new CC.Service.Webhost.Services.Announcement
                {
                    EventID = announcement.EventID,
                    Title = announcement.Title,
                    Content = announcement.Content,
                    PublishDate = announcement.PublishDate
                });

                return RedirectToAction("Index");
            }
            catch
            {
                // TODO: show the error

                return View(announcement);
            }
        }

        //
        // GET: /Announcement/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var announcement = service.GetAnnouncement(id);

            Announcement model = new Announcement()
            {
                ID = announcement.ID,
                EventID = announcement.EventID,
                Title = announcement.Title,
                Content = announcement.Content,
                PublishDate = announcement.PublishDate
            };

            return View(model);
        }

        //
        // POST: /Announcement/Edit/5

        [HttpPost]
        public ActionResult Edit(Announcement announcement)
        {
            try
            {
                service.UpdateAnnouncement(new CC.Service.Webhost.Services.Announcement
                {
                    ID = announcement.ID,
                    EventID = announcement.EventID,
                    Title = announcement.Title,
                    Content = announcement.Content,
                    PublishDate = announcement.PublishDate
                });

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // POST: /Announcement/Delete/5

        // [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                service.DeleteAnnouncement(id);

                return RedirectToAction("Index");
            }
            catch
            {
                var announcement = service.GetAnnouncement(id);

                Announcement model = new Announcement()
                {
                    ID = announcement.ID,
                    EventID = announcement.EventID,
                    Title = announcement.Title,
                    Content = announcement.Content,
                    PublishDate = announcement.PublishDate
                };

                return View("Details", model);
            }
        }
    }
}

CC.UI.Webhost/Views/Announcement/Create.cshtml
@using CC.UI.Webhost.Models;

@model Announcement

@{
    ViewBag.Title = "Create Announcement";
}

@*
<div>
    @Html.ActionLink("[back]", "Index")
</div>
*@

<div class="title">create announcement | @Html.ActionLink("back", "Index")</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.EventID)

    <div class="field-name">
        @Html.LabelFor(model => model.Title)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </div>

    <div class="field-name">
        @Html.LabelFor(model => model.Content)
    </div>
    <div class="editor-multiline-field">
        @Html.EditorFor(model => model.Content)
        @Html.ValidationMessageFor(model => model.Content)
    </div>

    <div class="field-name">
        @Html.LabelFor(model => model.PublishDate)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.PublishDate)
        @Html.ValidationMessageFor(model => model.PublishDate)
    </div>

    <br />
    
    <div>
        <input type="submit" value="Create" class="action-button"/>
    </div>
    
    <br />
}

<script type="text/javascript">
    $("input:text:visible:first").focus();
</script>

CC.UI.Webhost/Views/Announcement/Details.cshtml
@model CC.UI.Webhost.Models.Announcement

@{
    ViewBag.Title = "Announcement Details";
}

<h2>ViewPage1</h2>

<fieldset>
    <legend>Announcement</legend>

    <div class="display-label">Title</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">Content</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CC.UI.Webhost/Views/Announcement/Edit.cshtml
@using CC.UI.Webhost.Models;

@model Announcement

@{
    ViewBag.Title = "Edit Announcement";
}

@*
<div>
    @Html.ActionLink("[back]", "Index")
</div>
*@

<div class="title">edit announcement | @Html.ActionLink("back", "Index")</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) 
{
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.EventID)

    <div class="field-name">
        @Html.LabelFor(model => model.Title)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </div>

    <div class="field-name">
        @Html.LabelFor(model => model.Content)
    </div>
    <div class="editor-multiline-field">
        @Html.EditorFor(model => model.Content)
        @Html.ValidationMessageFor(model => model.Content)
    </div>

    <div class="field-name">
        @Html.LabelFor(model => model.PublishDate)
    </div>
    <div class="editor-field">
        @Html.EditorFor(model => model.PublishDate)
        @Html.ValidationMessageFor(model => model.PublishDate)
    </div>

    <br/>

    <div>
        <input type="submit" value="Save" class="action-button" />

        <input type="button" value="Delete" class="action-button" onclick="location.href='@Url.Action("Delete", "Announcement", new { id = Model.ID })'" />
    </div>

    <br/>
}

CC.UI.Webhost/Views/Announcement/Index.cshtml
@using CC.UI.Webhost.Models;

@model List<Announcement>

@{
    ViewBag.Title = "Announcements";
}

@*
<div>
    @Html.ActionLink("[back]", "Admin", "Home")
    @Html.ActionLink("[new]", "Create")
</div>
*@

<div class="title">announcements | @Html.ActionLink("new", "Create") | @Html.ActionLink("back", "Admin", "Home")</div>

@foreach (Announcement announcement in Model)
{
    <div>
        @Html.ActionLink(announcement.Title, "Edit", new { id = announcement.ID })
    </div>
}