CC.UI.Webhost/Models/Volunteer.cs
namespace CC.UI.Webhost.Models
{
    using System.Collections.Generic;

    public class Volunteer : Person
    {
        // public string FirstName { get; set; }

        // public string LastName { get; set; }

        // public IList<VolunteerActivity> VolunteerActivities { get; set; }
    }

    //public class VolunteerActivity
    //{
    //    public string ActivityName { get; set; }

    //    public DateTimeOffset ActivityTimeStart { get; set; }

    //    public IList<Volunteer> Volunteers { get; set; }
    //}
}

CC.UI.Webhost/Controllers/VolunteerController.cs
using System;
using CC.Service.Webhost.CodeCampSvc;

namespace CC.UI.Webhost.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using CC.Service.Webhost.Services;
    using Models;

    public class VolunteerController : BaseController
    {
        public VolunteerController(ICodeCampService service, ICodeCampServiceRepository repo) : base(service, repo) { }


        private const string CONST_TASK_PARAMETER_ID = "taskId";

        [Authorize(Roles = "Admin")]
        public ActionResult Index(int eventId)
        {
            var taskList = this.service.GetAllCurrentEventTasks(eventId);
            return View(FormatCurrentEventTasks(taskList));
        }

        private IList<VolunteerTask> FormatCurrentEventTasks(ICollection<Task> taskList)
        {
            IList<VolunteerTask> model = new List<VolunteerTask>();

            if (taskList != null)
            {
                model = new List<VolunteerTask>(taskList.Count());
                foreach (var task in taskList)
                {
                    model.Add(new VolunteerTask
                    {
                        Capacity = task.Capacity,
                        Description = task.Description,
                        StartTime = task.StartTime,
                        EndTime = task.EndTime,
                        Id = task.Id
                    });
                }                
            }
            return model;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create(int eventId)
        {
            var eventForTask = service.GetEvent(eventId);
            var taskStart = DateTime.Now;
            var taskEnd = DateTime.Now;
            
            if (eventForTask != null)
            {
                taskStart = eventForTask.StartTime;
                taskEnd = eventForTask.EndTime;
            }

            VolunteerTask task = new VolunteerTask { EventId = eventId, StartTime = taskStart, EndTime = taskEnd };
            return View(task);
        } 

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(VolunteerTask newTask)
        {
            try
            {
                service.AddTaskToEvent( new Task
                                            {
                                                StartTime = newTask.StartTime,
                                                EndTime = newTask.EndTime,
                                                Capacity = newTask.Capacity,
                                                EventID = newTask.EventId,
                                                Description = newTask.Description
                                            });
                return RedirectToAction("Index");
            }
            catch
            {
                return View(newTask);
            }
        }
        
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(int id)
        {
            var model = service.GetTaskById(id);
            return View(MapModel(model));
        }

        private VolunteerTask MapModel(Task model)
        {
            var vt = new VolunteerTask
            {
                Id = model.Id,
                StartTime = model.StartTime,
                EndTime = model.EndTime,
                Description = model.Description,
                Capacity = model.Capacity,
                Volunteers = new List<Volunteer>(model.Assignees.Count()),
            };

            if (model.Event != null)
            {
                vt.Event = new Models.Event {Name = model.Event.Name, ID = model.Event.ID};
            }

            if (model.Assignees != null)
            {
                model.Assignees
                     .ToList()
                     .ForEach(a => vt.Volunteers
                                     .Add(new Volunteer
                                              {
                                                  FirstName = a.FirstName, 
                                                  LastName = a.LastName,
                                              }));   
            }
            return vt;
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(VolunteerTask volunteerTask)
        {
            try
            {
                var task = service.GetTaskById(volunteerTask.Id);
                task.Name = volunteerTask.Name;
                task.Description = volunteerTask.Description;
                task.Capacity = volunteerTask.Capacity;
                task.StartTime = volunteerTask.StartTime;
                task.EndTime = volunteerTask.EndTime;
                task.EndTime = volunteerTask.EndTime;
                task.EventID = volunteerTask.EventId;
                service.UpdateTask(task);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id, FormCollection collection)
        {
            try
            {
                int taskId;
                var taskIdPassedInFromFormPost = Request[CONST_TASK_PARAMETER_ID];

                Int32.TryParse(taskIdPassedInFromFormPost, out taskId);

                if (taskId == 0)
                {
                    throw new ApplicationException("taskId is invalid.");
                }

                service.DisableTask(taskId);   
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CC.UI.Webhost/Views/Volunteer/Create.cshtml
@using System.Web.UI.HtmlControls
@model CC.UI.Webhost.Models.VolunteerTask

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@section AddToHead
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.datetimepicker.js")" type="text/javascript"></script>

    <link href="@Url.Content("~/Content/Javascript/jquery.datetimepicker.css")" rel="stylesheet" type="text/css" />

}

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>VolunteerTask</legend>

        @Html.HiddenFor(model => model.EventId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Capacity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Capacity)
            @Html.ValidationMessageFor(model => model.Capacity)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartTime)
        </div>

        <div class="editor-field">
            @Html.EditorFor(model => model.StartTime)
            @Html.ValidationMessageFor(model => model.StartTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EndTime)
        </div>

        <div class="editor-field">
            @Html.EditorFor(model => model.EndTime)
            @Html.ValidationMessageFor(model => model.EndTime)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CC.UI.Webhost/Views/Volunteer/Delete.cshtml
@model CC.UI.Webhost.Models.VolunteerTask

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>VolunteerTask</legend>

    <div class="display-label">EventId</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EventId)
    </div>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">Capacity</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Capacity)
    </div>

    <div class="display-label">StartTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StartTime)
    </div>

    <div class="display-label">EndTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EndTime)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CC.UI.Webhost/Views/Volunteer/Details.cshtml
@model CC.UI.Webhost.Models.VolunteerTask

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>VolunteerTask</legend>

    <div class="display-label">EventId</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EventId)
    </div>

    <div class="display-label">Name</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">Description</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">Capacity</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Capacity)
    </div>

    <div class="display-label">StartTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StartTime)
    </div>

    <div class="display-label">EndTime</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EndTime)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CC.UI.Webhost/Views/Volunteer/Edit.cshtml
@using System.Globalization
@model CC.UI.Webhost.Models.VolunteerTask

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@section AddToHead
{
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.datetimepicker.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/Javascript/jquery.datetimepicker.css")" rel="stylesheet" type="text/css" />
}


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>

        @Html.HiddenFor(model => model.Id)

        <div>
            @Html.DisplayTextFor(model => model.Event.Name)
        </div>
        <br/>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <br/>
        <div class="editor-label">
            @Html.LabelFor(model => model.Capacity)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Capacity)
            @Html.ValidationMessageFor(model => model.Capacity)
        </div>
        <br/>
        <div class="editor-label">
            @Html.LabelFor(model => model.StartTime)
        </div>
        <div class="editor-field">
            
            @Html.EditorFor(model => model.StartTime)
            @Html.ValidationMessageFor(model => model.StartTime)
        </div>
        <br/>
        <div class="editor-label">
            @Html.LabelFor(model => model.EndTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EndTime)
            @Html.ValidationMessageFor(model => model.EndTime)
        </div>
        <br/>

        <div>
            @using (Html.BeginForm("Delete", "Volunteer", FormMethod.Post, new { id = "disableForm"}))
            {
                <div id="disable">
                    <div id="disablebtn">
                        <button type="submit" id="disableSubmit" name="btnSubmit" value="disable" disabled="disabled">disable</button>
                    </div>
                    <div id="taskIdParameter">
                        @Html.Hidden("taskId", Model.Id.ToString(CultureInfo.InvariantCulture))
                    </div>
                </div>            
            }
        </div>

        <br/>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CC.UI.Webhost/Views/Volunteer/Index.cshtml
@using CC.UI.Webhost.Models
@model IList<CC.UI.Webhost.Models.VolunteerTask>

@{
    ViewBag.Title = "Index";
}

<div class="title">volunteer tasks | @Html.ActionLink("new", "Create") | @Html.ActionLink("back", "Admin", "Home")</div>

@foreach (VolunteerTask task in ViewData.Model)
{
        <div class="box">
            &nbsp; @Html.ActionLink(string.Format("{0} {1} - {2}", task.Description, task.StartTime.ToShortTimeString(), task.EndTime.ToShortTimeString()), "Edit", new { id = task.Id })
            <br/>
            &nbsp; Capacity: @string.Format("{0}", task.Capacity)    
        </div>
        <br/>
}

<script src="../../Scripts/jquery.animate-shadow-min.js" type="text/javascript"></script>
<script>
    $(function () {
        $('.box').animate({ boxShadow: '2 2 5px #6495ED' });
        // $('.box').animate({ boxShadow: '0 0 30px #44f' });
        // $('.box').onmouseover.stop().animate({boxShadow: '0 0 50px'}, 'fast');
        // $('.box').onmouseout.stop().animate({boxShadow: '0 0 0'}, 'fast');
    });
    
</script>

CC.UI.Webhost/Views/Volunteer/List.cshtml
@model IEnumerable<CC.UI.Webhost.Models.VolunteerTask>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            EventId
        </th>
        <th>
            Name
        </th>
        <th>
            Description
        </th>
        <th>
            Capacity
        </th>
        <th>
            StartTime
        </th>
        <th>
            EndTime
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capacity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>