CC.UI.Webhost/Models/SessionsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CC.UI.Webhost.Models
{
    public class SessionsViewModel
    {
        public SessionsViewModel()
        {
            Sessions = new List<Session>();
            Timeslots = new List<Timeslot>();
        }
        public List<Session> Sessions { get; set; }
        public List<Timeslot> Timeslots { get; set; } 
    }
}

CC.UI.Webhost/Controllers/SessionController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using CC.UI.Webhost.Models;
using System;
using System.Web.UI;
using CC.Service.Webhost.CodeCampSvc;

namespace CC.UI.Webhost.Controllers
{

    public class SessionController : BaseController
    {
        public SessionController(ICodeCampService service, ICodeCampServiceRepository repo) : base(service, repo) { }

        //
        // GET: /Session/

        public ActionResult Index()
        {
            return View("Details");
        }

        //
        // GET: //SpeakerSessions/

        [Authorize]
        public ActionResult SpeakerSessions(int eventid)
        {
            var sessions = service.GetSpeakerSessions(eventid, this.CurrentUser.ID);

            List<Session> model = new List<Session>();
            foreach (var session in sessions)
                model.Add(new Session()
                {
                    ID = session.ID,
                    Name = session.Name,
                    Description = session.Description,
                    Level = session.Level.ToString(),
                    Status = session.Status,
                    Location = string.IsNullOrEmpty(session.Location) ? string.Empty : session.Location
                });

            return View(model);
        }

        //
        // GET: /Session/Details/5

        public ActionResult Details(int id)
        {
            var session = service.GetSession(id);

            Session model = new Session()
            {
                ID = session.ID,
                EventID = session.EventID,
                SpeakerID = session.SpeakerID,
                Name = session.Name,
                Description = session.Description,
                Level = session.Level.ToString(),
                Speaker = session.Speaker,
                Status = session.Status,
                ImageUrl = session.ImageUrl,
                Image = session.Image,
                StartTime = string.Format("{0}", session.StartTime.HasValue ? session.StartTime.Value.ToShortTimeString() : "N/A"),
                EndTime = string.Format("{0}", session.EndTime.HasValue ? session.EndTime.Value.ToShortTimeString() : "N/A"),
                Location = string.IsNullOrEmpty(session.Location) ? string.Empty : session.Location
            };

            return View(model);
        }

        [Authorize]
        public ActionResult Attend(int id)
        {
            service.AttendSession(CurrentUser.ID, id);

            return RedirectToAction("MyAgenda", "Home");
        }

        //
        // GET: /Session/Create

        [Authorize]
        public ActionResult Create(int eventid)
        {
            var currentEvent = service.GetEvent(eventid);

            ViewBag.Event = currentEvent;
            var result = service.GetTags();
            ViewBag.Tags = result;
            return View("Create");
        }

        //
        // POST: /Session/Create

        [HttpPost]
        public ActionResult Create(int eventid, Session session)
        {
            ViewBag.Event = service.GetEvent(eventid);

            try
            {
                service.CreateSession(new CC.Service.Webhost.Services.Session()
                {
                    EventID = eventid,
                    SpeakerID = this.CurrentUser.ID,
                    Name = session.Name,
                    Description = session.Description,
                    Level = Int32.Parse(session.Level),
                    TagID = session.TagID.Value,
                    Status = "SUBMITTED",
                    Location = string.IsNullOrEmpty(session.Location) ? string.Empty : session.Location
                });

                return RedirectToAction("SpeakerSessions");
            }
            catch(Exception)
            {
                return View(session);
            }
        }

        //
        // GET: /Session/Edit/5

        [Authorize]
        public ActionResult Edit(int id)
        {
            var session = service.GetSession(id);
            var result = service.GetTags();
            ViewBag.Tags = result;

            if (session.SpeakerID == CurrentUser.ID)
            {
                Session model = new Session()
                {
                    ID = session.ID,
                    EventID = session.EventID,
                    SpeakerID = session.SpeakerID,
                    Name = session.Name,
                    Description = session.Description,
                    Level = session.Level.ToString(),
                    Speaker = session.Speaker,
                    Status = session.Status,
                    TagID = session.TagID,
                    Location = string.IsNullOrEmpty(session.Location) ? string.Empty : session.Location
                };

                return View(model);
            }
            else
            {
                return RedirectToAction("SpeakerSessions");
            }
        }

        //
        // POST: /Session/Edit/5

        [HttpPost]
        public ActionResult Edit(Session session)
        {
            try
            {
                var savedSession = service.GetSession(session.ID);
                savedSession.Name = session.Name;
                savedSession.Description = session.Description;
                savedSession.Level = Int32.Parse(session.Level);
                savedSession.TagID = session.TagID.Value;
                service.UpdateSession(savedSession);

                return RedirectToAction("SpeakerSessions");
            }
            catch
            {
                return View(session);
            }

        }


        //
        // POST: /Session/Delete/5

        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                service.DeleteSession(id);
                return RedirectToAction("SpeakerSessions");
            }
            catch
            {
                var session = service.GetSession(id);

                Session model = new Session()
                {
                    ID = session.ID,
                    EventID = session.EventID,
                    SpeakerID = session.SpeakerID,
                    Name = session.Name,
                    Description = session.Description,
                    Level = session.Level.ToString(),
                    Speaker = session.Speaker,
                    Status = session.Status,
                    Location = string.IsNullOrEmpty(session.Location) ? string.Empty : session.Location
                };

                return View("Details", model);
            }
        }
    }
}

CC.UI.Webhost/Controllers/SpeakerController.cs
using CC.Service.Webhost.CodeCampSvc;

namespace CC.UI.Webhost.Controllers
{
    using System.Web.Mvc;

    using CC.UI.Webhost.Models;
using System.Web.UI;

    public class SpeakerController : BaseController
    {
        public SpeakerController(ICodeCampService service, ICodeCampServiceRepository repo) : base(service, repo) { }

        //
        // GET: /Speaker/

        public ActionResult Index()
        {
            return View("Details");
        }

        //
        // GET: /Speaker/Details/5

        [OutputCache(Duration = 600, Location=OutputCacheLocation.Client, VaryByParam = "id")]
        public ActionResult Details(int eventid, int id)
        {
            var speaker = service.GetSpeaker(eventid, id);

            Speaker model = new Speaker()
            {
                ID = speaker.ID,
                Email = speaker.Email,
                FirstName = speaker.FirstName,
                LastName = speaker.LastName,
                Title = speaker.Title,
                Bio = speaker.Bio,
                Website = speaker.Website,
                Blog = speaker.Blog,
                Twitter = speaker.Twitter,
                ImageUrl = speaker.ImageUrl,
                Image = speaker.Image
            };

            foreach (var session in speaker.Sessions)
            {
                if (session.Status == "APPROVED")
                {
                    model.Sessions.Add(new Session()
                    {
                        ID = session.ID,
                        Name = session.Name,
                        Description = session.Description,
                        StartTime = session.StartTime.Value.ToShortTimeString(),
                        EndTime = session.EndTime.Value.ToShortTimeString(),
                        Location = string.IsNullOrEmpty(session.Location) ? string.Empty : session.Location
                    });
                }
            }

            return View(model);
        }

        //
        // GET: /Speaker/Create

        public ActionResult Create()
        {
            return View("Details");
        } 

        //
        // POST: /Speaker/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Details");
            }
        }
        
        //
        // GET: /Speaker/Edit/5
 
        public ActionResult Edit(int id)
        {
            // TODO: var speaker = service.GetSpeaker(id);
            // TODO: return View(speaker);

            return View("Details");
        }

        //
        // POST: /Speaker/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Details");
            }
        }

        //
        // GET: /Speaker/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View("Details");
        }

        //
        // POST: /Speaker/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View("Details");
            }
        }
    }
}

CC.UI.Webhost/Controllers/SponsorController.cs
using CC.Service.Webhost.CodeCampSvc;

namespace CC.UI.Webhost.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Web;
    using System.Web.Mvc;
    using CC.UI.Webhost.Models;
    using OCC.UI.Webhost.Utilities;
    using System.Linq;

    public class SponsorController : BaseController
    {

        public SponsorController(ICodeCampService service, ICodeCampServiceRepository repo) : base(service, repo) { }


        //
        // GET: /Sponsor/

        public ActionResult Index(int eventid)
        {
            var sponsors = service.GetSponsors(eventid);
            List<Sponsor> model = sponsors.Select(ServiceToWebHostSponsor).ToList();
            return View(model);
        }

        //
        // GET: /Sponsor/Details/5

        public ActionResult Details(int id)
        {
            var sponsor = service.GetSponsor(id);

            Sponsor model = new Sponsor()
            {
                ID = sponsor.ID,
                EventID = sponsor.EventID,
                Name = sponsor.Name,
                Description = sponsor.Description,
                SponsorshipLevel = sponsor.SponsorshipLevel,
                WebsiteUrl = sponsor.WebsiteUrl,
            };

            return View(model);
        }

        //
        // GET: /Sponsor/Create

        [Authorize(Roles = "Admin")]
        public ActionResult Create(int eventid)
        {
            Sponsor model = new Sponsor() { EventID = eventid };

            return View(model);
        }

        //
        // POST: /Sponsor/Create

        [HttpPost]
        public ActionResult Create(Sponsor sponsor)
        {
            try
            {
                service.CreateSponsor(new CC.Service.Webhost.Services.Sponsor()
                {
                    EventID = sponsor.EventID,
                    Name = sponsor.Name,
                    Description = sponsor.Description,
                    SponsorshipLevel = sponsor.SponsorshipLevel,
                    WebsiteUrl = sponsor.WebsiteUrl,
                    Image = ConvertToByes(Request.Files["Logo"])
                });

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View(sponsor);
            }
        }

        //
        // GET: /Sponsor/Edit/5

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var sponsor = service.GetSponsor(id);
            Sponsor model = ServiceToWebHostSponsor(sponsor);
            return View(model);
        }

        //
        // POST: /Sponsor/Edit/5

        [HttpPost]
        public ActionResult Edit(Sponsor sponsor)
        {
            try
            {
                service.UpdateSponsor(new CC.Service.Webhost.Services.Sponsor()
                {
                    ID = sponsor.ID,
                    EventID = sponsor.EventID,
                    Name = sponsor.Name,
                    Description = sponsor.Description,
                    SponsorshipLevel = sponsor.SponsorshipLevel,
                    WebsiteUrl = sponsor.WebsiteUrl,
                    Image = ConvertToByes(Request.Files["Logo"])
                });

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // POST: /Sponsor/Delete/5

        // [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            try
            {
                service.DeleteSponsor(id);

                return RedirectToAction("Index");
            }
            catch
            {
                var sponsor = service.GetSponsor(id);

                Sponsor model = new Sponsor()
                {
                    ID = sponsor.ID,
                    EventID = sponsor.EventID,
                    Name = sponsor.Name,
                    Description = sponsor.Description,
                    SponsorshipLevel = sponsor.SponsorshipLevel,
                    WebsiteUrl = sponsor.WebsiteUrl,
                };

                return View("Details", model);
            }
        }

        #region Private Helpers

        private byte[] ConvertToByes(HttpPostedFileBase image)
        {
            byte[] imageBytes = null;
            BinaryReader reader = new BinaryReader(image.InputStream);
            imageBytes = reader.ReadBytes((int)image.ContentLength);
            return imageBytes;
        }

        // Leaving fully qualified names here since it's kind of confusing having the two sponsor classes
        // named the same.  This way, it's clear.
        private CC.UI.Webhost.Models.Sponsor ServiceToWebHostSponsor(Service.Webhost.Services.Sponsor serviceSponsor)
        {
            return new CC.UI.Webhost.Models.Sponsor()
            {
                ID = serviceSponsor.ID,
                EventID = serviceSponsor.EventID,
                Name = serviceSponsor.Name,
                Description = serviceSponsor.Description,
                SponsorshipLevel = serviceSponsor.SponsorshipLevel,
                WebsiteUrl = serviceSponsor.WebsiteUrl,
                Logo = ImageUtils.ImageFromBytes(serviceSponsor.Image),
            };
        }

        #endregion
    }
}

CC.UI.Webhost/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CC.Service.Webhost.CodeCampSvc;
using CC.UI.Webhost.Models;

namespace CC.UI.Webhost.Controllers
{
    public class TagController : BaseController
    {

        public TagController(ICodeCampService service, ICodeCampServiceRepository repo) : base(service, repo) { }


        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var tagCollection = service.GetTags();
            var model = tagCollection.Select(tag => new Tag()
            {
                Id = tag.ID, 
                SessionsCount = tag.SessionsCount, 
                TagName = tag.TagName

            }).ToList();

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int tagId)
        {
            var result = service.DeleteTag(tagId);
            
            return RedirectToAction("Index");
            
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Add(Tag tag)
        {

            var newTag = new CC.Service.Webhost.Services.Tag()
            {
                ID = tag.Id,
                TagName = tag.TagName 
            };

            service.AddTag(newTag);

            return RedirectToAction("Index");
            
        }

    }
}

CC.UI.Webhost/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}

<div class="title">admin</div>

<div>@Html.ActionLink("Administrators", "Index", "Administrator")</div>

<div>@Html.ActionLink("Events", "Index", "Event")</div>

<div>@Html.ActionLink("Announcements", "Index", "Announcement")</div>

<div>@Html.ActionLink("Sponsors", "Index", "Sponsor")</div>

<div>@Html.ActionLink("Tracks", "Index", "Track")</div>

<div>@Html.ActionLink("Timeslots", "Index", "Timeslot")</div>

<div>@Html.ActionLink("Schedule", "Index", "Schedule")</div>

<div>@Html.ActionLink("Volunteer Tasks", "Index", "Volunteer")</div>

<div>@Html.ActionLink("Mailing Lists", "Index", "MailingList")</div>

<div>@Html.ActionLink("Tags", "Index", "Tag")</div>

CC.UI.Webhost/Views/Home/Agenda.cshtml
@using CC.UI.Webhost.Models;

@model List<Track>

@{
    ViewBag.Title = "Agenda";
    Layout = "~/Views/Shared/_Layout.Responsive.cshtml";
}

<div class="title">agenda | @Html.ActionLink("my agenda", "MyAgenda")</div>

@*
    <div>
    <a href="@Url.Content("~/Content/Documents/SeattleCodeCamp2012Agenda.pdf")">Click here </a> for a PDF version of the agenda.
    </div>
*@

<table>

@foreach (var track in ViewData.Model)
{
    <tr>
        <td colspan="3">
            <div class="field-name">@track.Name</div>
        </td>
    </tr>
    
    foreach (var session in track.Sessions)
    {
        <tr>
            <td>
                <div>@session.StartTime - @session.EndTime</div>
            </td>
            <td>
                @Html.ActionLink(session.Name, "Details", "Session", new { id = session.ID }, null) -
                @Html.ActionLink(session.Speaker, "Details", "Speaker", new { id = session.SpeakerID }, null)
            </td>
        </tr>
    }

}

</table>

CC.UI.Webhost/Views/Home/FAQ.cshtml
@{
    ViewBag.Title = "FAQ";
}

<div class="title">F.A.Q.</div>

<div>
    <p>
        Q. When and where is Seattle Code Camp?<br />
        A. The 15th Annual Seattle Code Camp will he held on September 10th, 2016 at Seattle University located at 901 12th Avenue, Seattle, WA 98122.
    </p><p>&nbsp;</p>
</div>

<div>
    <p>
        Q. What is Seattle Code Camp?<br />
        A. Seattle Code Camp is one day learning event for programming professionals and students with a focus on coding, databases and related technologies. This is a "grass roots" mini application platform developer conferences, free to attendees and open to presenters of all stripes and experience.
    </p><p>&nbsp;</p>
</div>

<div>
    <p>
        Q. How much does it cost to attend?<br />
        A. Code Camp is free to attendees. Attendees will also be provided with free breakfast, lunch, and snacks throughout the day.
    </p><p>&nbsp;</p>
</div>
<div>
    <p>
        Q. Who is behind the Seattle Code Camp?<br />
        A. The Seattle Code Camp is organized by the <a href="http://dotnetda.org">.NET Developers Association</a>.
    </p><p>&nbsp;</p>
</div>

<div>
    <p>
        Q. Who can attend?<br />
        A. Anyone interested in the <a href="http://seattlecc.azurewebsites.net/Home/Sessions">sessions</a> can <a href="http://seattlecc.azurewebsites.net/Account/LogOn">signup to attend</a>. Attendees can signup beginning August 1st 2016 until the day before Code Camp.
    </p><p>&nbsp;</p>
</div>

<div>
    <p>
        Q. How does speaker approval process work?<br />
        A. Individual with expertise in any area/technology may @Html.ActionLink("signup to speak", "SpeakerSessions", "Session"). We welcome speakers of all experience levels including first time speakers. Speaker signup starts on June 7th, 2016. A speaker may submit multiple sessions but we usually only approve one session per speaker. We strive to notify accepted speakers as soon as possible after the closing date.  We promise you'll be notified no later than August 7th 2016. If for some reason, speakers are unable to fulfil their commitment we ask that you contact us immediately at <a href="mailto:speakers@seattle.codecamp.us">speakers@seattle.codecamp.us</a>.
    </p><p>&nbsp;</p>
</div>

<div>
    <p>
        Q. Do you provide room and boarding?<br />
        A. Code Camp is a voluntary event with the meals/refreshments paid by sponsors. We do not pay for room and boarding for our attendees or speakers.
    </p><p>&nbsp;</p>
</div>

<div>
    <p>
        Q. Do you have any special hotel deals for out-of-town attendees/speakers?<br />
        A. We do not.
    </p><p>&nbsp;</p>
</div>
<div>
    <p>
        Q. Where can I find sponsorship information?<br />
        A. Check out the <a href="https://1drv.ms/b/s!AhwIRzV5J8HVh-1-QGJeEQAOoM97uA" target="_blank">sponsor package</a>.
    </p><p>&nbsp;</p>
</div>

CC.UI.Webhost/Views/Home/MyAgenda.cshtml
@using CC.UI.Webhost.Models;

@model List<Session>

@{
    ViewBag.Title = "My Agenda";
}

<div class="title">my agenda | @Html.ActionLink("agenda", "Agenda")</div>

<p><strong>Note:&nbsp;</strong>Print this page out for your own convenience</p>
<p><strong>Note:&nbsp;</strong>You can now add multiple sessions to one timeslot so you can have backups</p>

<br/>
<br/>

@if (ViewData.Model.Count > 0)
{
    
<table>
    <tr>
        <td>Time</td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td>Location</td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td>Session</td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td>Speaker</td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td>Remove</td>
    </tr>

    @foreach (var session in ViewData.Model)
    {
        <tr>
            <td nowrap="nowrap">
                <div style="font-size: small">@session.StartTime - @session.EndTime</div>
            </td>
            <td>&nbsp;&nbsp;&nbsp;</td>
            <td>
                <div style="font-size: small">@session.Location</div>
            </td>
            <td>&nbsp;&nbsp;&nbsp;</td>
            <td>
                @Html.ActionLink(session.Name, "Details", "Session", new {id = session.ID}, null)
            </td>
            <td>&nbsp;&nbsp;&nbsp;</td>
            <td>
                @Html.ActionLink(session.Speaker, "Details", "Speaker", new {id = session.SpeakerID}, null)
            </td>
            <td>&nbsp;&nbsp;&nbsp;</td>
            <td>
                @Html.ActionLink("X", "RemoveFromMyAgenda", "Home", new { id = session.ID }, null)
            </td>
        </tr>
    }

</table>

}

<br />

<div class="title">Common Agenda:</div>
<div>
7:30 am : Registration opens<br />
8:00 am : Announcements, Welcome<br/>
8:30 am : Morning Sessions<br />
12:00 pm : Lunch<br/>
1:00 pm : Afternoon Sessions<br />
4:45 pm: Closing Remarks & Raffle<br />
</div>

CC.UI.Webhost/Views/Home/Sessions.cshtml
@using CC.UI.Webhost.Models;

@model SessionsViewModel

@{
    ViewBag.Title = "Sessions";
    var count = 0;
}

<div class="title">sessions</div>



@if (ViewBag.Event.IsSpeakerRegistrationOpen)
{
    <div>
        The following sessions have been submitted, but not yet approved.
    </div>
    <div style="clear: both"></div>
    <div>&nbsp;</div>
    <div style="clear: both"></div>
}
else
{ 
<div>
    <span>Timeslots:</span><br />
    @Html.ActionLink("All", "sessions", "home", new {id = -1}, null)<span>&nbsp;</span>
    @foreach (var slot in ViewData.Model.Timeslots.OrderBy(t => t.StartTime))
    {
        @Html.ActionLink(slot.StartTime.ToString("h:mm tt") +"-"+ slot.EndTime.ToString("h:mm tt"), "sessions", "home", new { id = slot.ID }, null)<span>&nbsp;</span>
    }
</div>
}
@foreach (var session in ViewData.Model.Sessions)
{
    <div style="clear: both"></div>
    <div>&nbsp;</div>
    <div style="clear: both"></div>
    @*}*@
    <div style="float:left;width: 95%">
        <div style="float: left; width: 48px">
            <a href="@Url.Action("Details", "Speaker", new { id = session.SpeakerID })">
                <div>
                    @Html.AvatarImageTag(session.Image, session.ImageUrl, session.Speaker, 48, 48, session.Speaker)
                    <div style="position: relative; top: 0px; left: 0px;"><small>@session.Speaker</small>
                    </div>
                </div>
            </a>
        </div>

        <div style="float: left; padding-left: 20px; width: 80%">
            @Html.ActionLink(session.Name, "Details", "Session", new { id = session.ID }, null)&nbsp;@(string.IsNullOrEmpty(session.Location)?string.Empty:string.Format("(Room: {0})",session.Location))<br />
            <text>@session.Description.Substring(0,Math.Min(200,session.Description.Length))...</text>
            @if (session.Status == "APPROVED")
            {
                <small>@Html.ActionLink("Add to My Agenda", "Attend", "Session", new { id = (int)session.ID }, null) </small>
            }
        </div>

    </div>
    count = count + 1;
}

CC.UI.Webhost/Views/Home/Speakers.cshtml
@using CC.UI.Webhost.Models;

@model List<Speaker>

@{
    ViewBag.Title = "Speakers";
    var alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToCharArray();
    var count = 1;
}

<div class="title">speakers</div>
<a name="top">&nbsp;</a><br />

@if (ViewBag.Event.IsSpeakerRegistrationOpen)
{
    <div>
        Click @Html.ActionLink("here", "SpeakerSessions", "Session") here for speaker registration. 
        <br />
        The following speakers have signed up to speak at the event. Sessions are not yet approved.
    </div>
        <div style="clear: both"></div>
            <div>&nbsp;</div>
        <div style="clear: both"></div>
}

    <div>
@foreach (var speaker in ViewData.Model)
{
            <div style="float:left;width:60px">
                <a href="@Url.Action( "Details", "Speaker", new { id = speaker.ID })">
                    <div>
                        @Html.AvatarImageTag(speaker.Image, speaker.ImageUrl, speaker.FullName, 60, 60, speaker.FullName)
                        <div style="position: relative; top: 0px; left: 0px;">@speaker.FullName
                        </div>
                    </div>
                </a>
            </div>
            <div style="float:left;width:60px">
                &nbsp;
            </div>


        if (count % 5 == 0)
        {
        <div style="clear: both"></div>
        <div>&nbsp;</div>
        <div style="clear: both"></div>
        }
    count++;
}

    </div>

CC.UI.Webhost/Views/Home/Sponsors.cshtml
@using CC.UI.Webhost.Models;

@model List<Sponsor>

@{
    ViewBag.Title = "Sponsors";
    var counter = 0;
}

<div class="title">sponsors</div>

@if (ViewBag.Event.IsSponsorRegistrationOpen)
{
    <div>
        Interested in sponsoring our event?  <a href="@Url.Content("~/Content/Documents/Seattle Code Camp 2016 Contributor Information.pdf")">Click here </a> to view our sponsor package.
    </div>
}
<div>&nbsp;</div>


@foreach (var sponsor in ViewData.Model)
{
    counter++;
    <div style="float:left;width:275px;padding-right:20px">
        <div class="field-value"><strong>@sponsor.Name</strong></div>
        <div class="field-value">@sponsor.SponsorshipLevel</div>
        <div class="field-value">
            <div style="width: 250px">
                @if (sponsor.Logo != null)
                {
                    <a href="@sponsor.WebsiteUrl" target="_blank">
                        <img style="max-width: 100%;" src="data:image;base64,@System.Convert.ToBase64String(sponsor.Logo.GetBytes())" alt="@sponsor.Name" />
                    </a>
                }
            </div>
        </div>
    </div>
    if ((counter % 2) == 0)
    {
        <div style="clear:both"></div>
        <div>&nbsp;</div>
        <div style="clear:both"></div>
    }
}

CC.UI.Webhost/Views/Home/Venue.cshtml
@using CC.UI.Webhost.Models;

@model Event

@{
    ViewBag.Title = "Venue";
}

<div class="title">venue</div>

@*
    <div>TODO: fix bing map</div>
*@

<div id="mapviewer"><div><iframe width="500" height="400" frameborder="0" src="https://www.bing.com/maps/embed/viewer.aspx?v=3&cp=47.609601~-122.316972&lvl=18&w=500&h=400&sty=r&typ=d&pp=&ps=&dir=0&mkt=en-us&src=SHELL&form=BMEMJS"></iframe><div style="margin: 12px 0 0 0;"><a target="_blank" href="https://www.bing.com/maps/?cp=47.609601~-122.316972&sty=r&lvl=18&sp=&mm_embed=map">View Larger Map</a>&nbsp; |&nbsp; <a target="_blank" href="https://www.bing.com/maps/?cp=47.609601~-122.316972&sty=r&lvl=18&rtp=~pos.47.609601_-122.316972____&mm_embed=dir">Get Directions</a>&nbsp; |&nbsp; <a target="_blank" href="https://www.bing.com/maps/?cp=ry1f634t66td&sty=b&lvl=18&sp=&mm_embed=be">View Bird's Eye</a></div></div></div>

<pre>
@ViewData.Model.Location
@ViewData.Model.Address1
@ViewData.Model.Address2
@ViewData.Model.City @ViewData.Model.State @ViewData.Model.Zip
</pre>
@*<h2>FREE parking</h2>*@
@*<div>
    The garages at Murphy, Broadway or the main visitor lots can be used. There will be parking attendants at Murphy and Broadway garages from 7-10 am. Attendees should say they are there with Seattle CodeCamp and will receive a permit. After 10 am all attendees need to go to main visitor lot at 12th and Marion to get a pass. You may park in P3, P4 or P5.
    <a href="https://www.seattleu.edu/uploadedFiles/Transportation_and_Parking_Services/Content/Parking/SU-Campus-Map.pdf" target="_blank">See garage maps</a>
</div>*@